name: apprentissage
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.19.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  hive:
  hive_flutter:
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fl_chart: ^0.62.0
  url_launcher: ^6.1.11
  path_provider: ^2.0.15
  flutter_mailer: ^2.0.2
  lottie: ^2.3.2
dev_dependencies:
  hive_generator:
  build_runner:
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
  fonts:
    - family: RodeeoPrimary
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500

    - family: RodeeoSecondary
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
